version: "3.7"

networks:
  net:
    driver: overlay
    attachable: true

services:
  # HTTPS server that routes PHP calls to app:9000
  nginx:
    image: nginx:alpine
    networks:
      - net
    ports:
      - target: 80
        published: "${NGINX_HTTP_PORT:-80}"
        protocol: tcp
        mode: host
      - target: 443
        published: "${NGINX_HTTPS_PORT:-443}"
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: ./nginx/php-fpm.conf
        target: /etc/nginx/php-fpm.conf
        read_only: true
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      # - type: bind
      #   source: ./letsencrypt
      #   target: /etc/letsencrypt
      #   read_only: true
      # - type: bind
      #   source: ./acme
      #   target: /var/www/acme
      # - type: bind
      #   source: "${APP_ROOT:-..}"
      #   target: /var/www/html
      - type: bind
        source: ./html
        target: /var/www/html

  app:
    image: roundcube/roundcubemail:latest-fpm-alpine
    networks:
      - net
    environment:
      ROUNDCUBE_DEFAULT_HOST: tls://172.18.0.1
      ROUNDCUBE_SMTP_SERVER: tls://172.18.0.1
    volumes:
      - type: bind
        source: ./html
        target: /var/www/html
